version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
    # Configure version update behavior
    versioning-strategy: auto
    # Configure commit message
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all updates together
    groups:
      actions:
        patterns:
          - "*"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "github_actions"
      - "automerge"
    # Configure commit message
    commit-message:
      prefix: "ci"
      include: "scope"
