name = "project"
main = "src/worker.js"
compatibility_date = "2024-02-22"
workers_dev = true

[assets]
directory = "dist"

[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "dc953a65f10c424d94803328e066b5a9"
preview_id = "28111915119942eca5dc83a27d0a4ca7"

# Non-sensitive environment variables
[vars]
ENVIRONMENT = "production"
STRIPE_MODE = "test"
S3_REGION = "local"
SUPABASE_URL = "https://gnwdahoiauduyncppbdb.supabase.co"

[env.production.vars]
ENVIRONMENT = "production"
STRIPE_MODE = "test"
S3_REGION = "local"
SUPABASE_URL = "https://gnwdahoiauduyncppbdb.supabase.co"

# The following secrets should be set using:
# npx wrangler secret put SECRET_NAME
# - SUPABASE_URL
# - SUPABASE_ANON_KEY
# - JWT_SECRET
# - STRIPE_WEBHOOK_SECRET
# - STRIPE_PUBLISHABLE_KEY
# - STRIPE_SECRET_KEY
# - OPENAI_API_KEY
# - S3_Access_Key
# - S3_Secret_Key

[build]
command = "npm run build"
watch_dir = "src"
upload.format = "service-worker" 