# SmartDebtFlow Worker Configuration
name = "project"
main = "src/worker.js"
compatibility_date = "2024-02-22"
workers_dev = true

# Domain Routes Configuration for main worker
routes = [
  "www.smartdebtflow.com/*",
  "smartdebtflow.com/*"
]

[build]
command = "npm run build"
watch_dir = "src"

# Site configuration - this automatically creates an ASSETS binding for the worker
[site]
bucket = "dist"

# Explicitly add ASSETS binding for clarity
# Note: This binding is automatically created by Workers when using [site],
# but we're making it explicit to avoid confusion
# [[bindings]]
# name = "ASSETS"
# type = "assets"

[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "dc953a65f10c424d94803328e066b5a9"
preview_id = "28111915119942eca5dc83a27d0a4ca7"

[[kv_namespaces]]
binding = "CACHE_STORAGE"
id = "fc94361a012149a786110694590856af"
preview_id = "d6fecc982467413a96246f7ac901db8b"

# Non-sensitive environment variables
[vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://gnwdahoiauduyncppbdb.supabase.co"
ASSETS_URL = ""

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://gnwdahoiauduyncppbdb.supabase.co"
ASSETS_URL = ""

# Set these secrets using 'npx wrangler secret put SECRET_NAME'
# - STRIPE_SK_TEST
# - STRIPE_SK_LIVE
# - SUPABASE_SERVICE_ROLE
# - SUPABASE_ANON_KEY
# - S3_ACCESS_KEY
# - S3_SECRET_KEY
# - SERVICE_JWT_SECRET
# - WEBHOOK_SECRET 

# AI Worker Configuration
[env.ai]
name = "curly-tooth-d4a2"
main = "src/ai-worker.js"
compatibility_date = "2024-02-22"
workers_dev = true

# Add KV namespaces to the AI environment as they are not inherited
[[env.ai.kv_namespaces]]
binding = "STATIC_ASSETS"
id = "dc953a65f10c424d94803328e066b5a9"
preview_id = "28111915119942eca5dc83a27d0a4ca7"

[[env.ai.kv_namespaces]]
binding = "CACHE_STORAGE"
id = "fc94361a012149a786110694590856af"
preview_id = "d6fecc982467413a96246f7ac901db8b"

# AI Worker Environment Variables
[env.ai.vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://gnwdahoiauduyncppbdb.supabase.co"
ASSETS_URL = ""

# Custom build command for AI worker - skip the build step since we don't need to build the frontend
[env.ai.build]
command = ""
watch_dir = "src"

# Routes for the AI Worker
[[env.ai.routes]]
pattern = "www.smartdebtflow.com/api/ai*"
zone_name = "smartdebtflow.com" 