# SmartDebtFlow Worker Configuration
name = "project"
main = "src/worker.js"
compatibility_date = "2024-02-22"
workers_dev = true

[build]
command = "npm run build"
watch_dir = "src"

# Site configuration - this automatically creates an ASSETS binding for the worker
[site]
bucket = "dist"

# Static assets configuration should be removed from [site]
# [site.assets]
# browser_TTL = 86400
# serve_single_page_app = true

# Explicitly add ASSETS binding for clarity
# Note: This binding is automatically created by Workers when using [site],
# but we're making it explicit to avoid confusion
# [[bindings]]
# name = "ASSETS"
# type = "assets"

[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "dc953a65f10c424d94803328e066b5a9"
preview_id = "28111915119942eca5dc83a27d0a4ca7"

[[kv_namespaces]]
binding = "CACHE_STORAGE"
id = "fc94361a012149a786110694590856af"
preview_id = "d6fecc982467413a96246f7ac901db8b"

# Removing R2 bucket configuration since we use Supabase Storage
# [[r2_buckets]]
# binding = "USER_CONTENT"
# bucket_name = "smart-debt-flow-user-content"

# Move Domain Routes Configuration outside of kv_namespaces
routes = [
  "www.smartdebtflow.com/*",
  "smartdebtflow.com/*"
]

# Non-sensitive environment variables
[vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://sdagcazfszlumwbatfcr.supabase.co"
ASSETS_URL = ""

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://sdagcazfszlumwbatfcr.supabase.co"
ASSETS_URL = ""

# Set these secrets using 'npx wrangler secret put SECRET_NAME'
# - STRIPE_SK_TEST
# - STRIPE_SK_LIVE
# - SUPABASE_SERVICE_ROLE
# - SUPABASE_ANON_KEY
# - S3_ACCESS_KEY
# - S3_SECRET_KEY
# - SERVICE_JWT_SECRET
# - WEBHOOK_SECRET 