name = "project"
main = "src/worker.js"
compatibility_date = "2024-02-22"
workers_dev = true

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = "dist"

# Remove this as it's not a recognized configuration
# assets_handler = true

[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "dc953a65f10c424d94803328e066b5a9"
preview_id = "28111915119942eca5dc83a27d0a4ca7"

[[kv_namespaces]]
binding = "CACHE_STORAGE"
id = "fc94361a012149a786110694590856af"
preview_id = "d6fecc982467413a96246f7ac901db8b"

# Removing R2 bucket configuration since we use Supabase Storage
# [[r2_buckets]]
# binding = "USER_CONTENT"
# bucket_name = "smart-debt-flow-user-content"

# Non-sensitive environment variables
[vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://sdagcazfszlumwbatfcr.supabase.co"
ASSETS_URL = ""

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
STRIPE_MODE = "live"
S3_REGION = "us-east-1"
SUPABASE_URL = "https://sdagcazfszlumwbatfcr.supabase.co"
ASSETS_URL = ""

# Set these secrets using 'npx wrangler secret put SECRET_NAME'
# - STRIPE_SK_TEST
# - STRIPE_SK_LIVE
# - SUPABASE_SERVICE_ROLE
# - SUPABASE_ANON_KEY
# - S3_ACCESS_KEY
# - S3_SECRET_KEY
# - SERVICE_JWT_SECRET
# - WEBHOOK_SECRET 